# todo: make it differ from baseasteroidmob... somehow???
- type: entity
  id: LavalandMobBase
  parent:
  - BaseMob
  - MobDamageable
  - MobAtmosExposed
  - MobCombat
  abstract: true
  components:
  - type: Reactive
    groups:
      Flammable: [ Touch ]
      Extinguish: [ Touch ]
      Acidic: [ Touch, Ingestion ]
  - type: Body
    prototype: Animal
  - type: Climbing
  - type: NameIdentifier
    group: GenericNumber
  - type: StatusEffects
    allowed:
    - SlowedDown
    - Stun
    - Electrocution
    - TemporaryBlindness
    - RadiationProtection
    - Drowsiness
  - type: Tag
    tags:
    - DoorBumpOpener
