# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2022 Morber <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Peptide90 <78795277+Peptide90@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 EmoGarbage404 <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Whisper <121047731+QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 JoeHammad1844 <130668733+JoeHammad1844@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Flareguy <78941145+Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nim <128169402+Nimfar11@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Kit0vras <123590995+Kit0vras@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Unkn0wn_Gh0st <shadowstalkermll@gmail.com>
# SPDX-FileCopyrightText: 2024 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 RealFakeSoof <william_r_dunn@yahoo.com>
# SPDX-FileCopyrightText: 2024 Hanz <41141796+Hanzdegloker@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 Alpha-Two <92269094+Alpha-Two@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 blobadoodle <me@bloba.dev>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTLeader
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives". Is never used anywhere else.
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    # - MagazineMagnum - No need

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives". Is never used anywhere else.
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - MagazineMagnum

- type: startingGear
  id: ERTLeaderGearEVAAnnie # Goobstation
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: FlashlightSeclite
    pocket2: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives". Is never used anywhere else.
  inhand:
  - WeaponRifleAnnie # Goobstation - DEATH TO LECTER ERT!!
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - MagazineLightRifle
    - MagazineLightRifle
    # - MagazineMagnum - Literally doesn't spawn with a gun that uses this. Seriously, who made this?

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHatFez
    eyes: ClothingEyesGlasses
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    - DrinkWaterMelonJuiceJug
    - Lantern
    - Lantern
    - Bible
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter
    - ExecutiveIDCard # Goobstation - Executive Access!

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlasses
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: Flare
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    - DrinkWaterMelonJuiceJug
    - Lantern
    - Lantern
    - Bible
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter
    - ExecutiveIDCard # Goobstation - Executive Access!

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTEngineer
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: Flare
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTSecurity
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
   # - MagazinePistol

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPulsePistol # Death to Crew aligned Ballistics
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
   # - MagazinePistol

# Every time an admin spawns a lecter ERT instead of an annie ert i lose a part of my soul. USE THE DAMN GUN MADE FOR THE ERTS, OR SPAWN THE OTHER PROTO. THIS IS REDUNDANT!!
# - type: startingGear
#   id: ERTSecurityGearEVALecter
#  equipment:
#    jumpsuit: ClothingUniformJumpsuitERTSecurity
#    back: ClothingBackpackERTSecurity
#    shoes: ClothingShoesBootsCombatFilled # STOP GIVING ROLES ADVANCED MAGBOOTS!! - SOL
#    mask: ClothingMaskGasERT
#    neck: ExecutiveIDCard # Goobstation - Executive Access!
#    eyes: ClothingEyesGlassesSecurity
#    gloves: ClothingHandsGlovesCombat
#    outerClothing: ClothingOuterHardsuitERTSecurity
#    id: ERTSecurityPDA
#    ears: ClothingHeadsetAltCentCom
#    belt: ClothingBeltSecurityFilled
#    pocket1: MagazineRifle
#    pocket2: MagazineRifle
#  inhand:
#    - WeaponRifleLecter
#  storage:
#    back:
#    # - WeaponDisabler - Redundant. It spawns in secbelts now.
#    - MedkitCombatFilled # Goobstation - No reason not to.
#    - BoxZiptie
#    - CrowbarRed
#    - MagazinePistol

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTMedic
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Goobstation
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbingFilledMedical # Fancier
    pocket1: Flare
    pocket2: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - CentCommHypo
    - MedkitAdvancedFilled
    - CrowbarRed
    - OmnizineChemistryBottle
    - JugOxandrolone
    - JugSalicylicAcid
    - ParamedHypo
    - CartridgeAtropine
    - CartridgeAtropine

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Goobstation
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbingFilledMedical # Fancier
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - CentCommHypo
    - MedkitAdvancedFilled
    - CrowbarRed
    - JugOxandrolone
    - JugSalicylicAcid
    - ParamedHypo
    - CartridgeAtropine
    - CartridgeAtropine

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem