# SPDX-FileCopyrightText: 2024 Aidenkrz <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Golinth <amh2023@gmail.com>
# SPDX-FileCopyrightText: 2024 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Baptr0b0t <152836416+Baptr0b0t@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Arendian <137322659+Arendian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Soup-Byte07 <135303377+Soup-Byte07@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
- type: securityIcon
  id: SecurityIcon
  abstract: true
  priority: 3
  offset: 1
  locationPreference: Right
  isShaded: true

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconPerma
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_perma

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconSearch
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_search

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconDangerous
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_dangerous

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconDischarged
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_discharged

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconIncarcerated
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_incarcerated

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconParoled
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_paroled

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconSuspected
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_suspected

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconWanted
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_wanted

- type: securityIcon
  id: MindShieldIcon
  priority: 2
  locationPreference: Right
  layer: Mod
  isShaded: true
  icon:
    sprite: /Textures/Interface/Misc/job_icons.rsi
    state: MindShield