# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 BombasterDS2 <shvalovdenis.workmail@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
- type: entity
  name: tracker box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxTracker
  description: A box containing a couple trackers.
  components:
  - type: StorageFill
    contents:
    - id: TrackingImplanter # Todo - Replace with biochip?
      amount: 4
  - type: Sprite
    layers:
    - state: box
