name: Build & Check Usings

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]
    paths:
      - '**/*.cs'

jobs:
  build-and-check:
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.6.0

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Pull Engine Updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0.x

    - name: Install Dependencies
      run: dotnet restore

    - name: Get Changed Files
      id: changed-files
      run: |
        git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} -- '*.cs' > changed-files.txt
        if [ -s changed-files.txt ]; then
          echo "::set-output name=files::$(cat changed-files.txt | tr '\n' ' ')"
        else
          echo "::set-output name=files::"
        fi
      shell: bash

    - name: Check Unnecessary Usings
      if: steps.changed-files.outputs.files != ''
      run: dotnet format --verify-no-changes --include ${{ steps.changed-files.outputs.files }}
      env:
        DOTNET_ROOT: /usr/share/dotnet

    - name: Show Usings Check Results
      if: failure()
      run: echo "Unnecessary usings or other formatting issues were found. Please fix them and push the changes."

  ci-success:
    name: Build Succeeded
    needs:
      - build-and-check
    runs-on: ubuntu-latest
    steps:
      - name: CI Success
        run: exit 0
