# SPDX-FileCopyrightText: 2024 SlamBamActionman <83650252+SlamBamActionman@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Vasilis <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: "Labels: Untriaged"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      if: join(github.event.issue.labels) == ''
      with:
        labels: "S: Untriaged"